FROM maven:3.6-openjdk-8 AS build
WORKDIR /app
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /app/boxfuse-sample-java-war-hello-war-hello
RUN mvn -f /app/boxfuse-sample-java-war-hello-war-hello/pom.xml clean package
FROM tomcat:8-jdk8-corretto
COPY --from=build /app/boxfuse-sample-java-war-hello-war-hello/target/hello-*.war /usr/local/tomcat/webapps/