---
# tasks file for prod
- name: Ensure tomcat is installed
  apt:
    name: tomcat9
    state: present

- name: Deploy artifact
  synchronize:
    src: "{{ artifact_src_path }}"
    dest: "{{ artifact_dest_path }}"
    private_key: "/home/theo_vi/.ssh/id_rsa"
    rsync_opts:
      - "--chown:tomcat:tomcat"
  delegate_to: "{{ build_ip }}"
  notify:
  - name: restart tomcat9